import { useEffect, useState } from 'react';
import api, { messageFromError } from '../../services/api';
import Section from '../../components/Section';
import StatCard from '../../components/StatCard';

export default function CustomerDashboard() {
  const [vouchers, setVouchers] = useState([]); const [cards, setCards] = useState([]); const [history, setHistory] = useState([]); const [giftHistory, setGiftHistory] = useState([]); const [notice, setNotice] = useState('');
  async function load() { try { const [v, c, h, gh] = await Promise.all([api.get('/vouchers/available'), api.get('/gift-cards/available'), api.get('/redemptions/my-history'), api.get('/gift-cards/my-history')]); setVouchers(v.data); setCards(c.data); setHistory(h.data); setGiftHistory(gh.data); } catch (e) { setNotice(messageFromError(e)); } }
  useEffect(() => { load(); }, []);
  async function redeemVoucher(code) { try { await api.post('/redemptions', { code }); setNotice(`Voucher ${code} redeemed.`); load(); } catch (e) { setNotice(messageFromError(e)); } }
  async function redeemCard(card) { const amount = Number(window.prompt(`Amount to redeem from ${card.code}`, '10')); if (!amount) return; try { await api.post('/gift-cards/redeem', { code: card.code, amount }); setNotice(`Gift card ${card.code} redeemed.`); load(); } catch (e) { setNotice(messageFromError(e)); } }
  return <div className="dashboard"><div className="hero-row"><div><span className="eyebrow">CUSTOMER WALLET</span><h1>Good benefits, clearly visible.</h1><p>Browse active offers and use them before they expire.</p></div><div className="stats"><StatCard label="Offers" value={vouchers.length + cards.length} /><StatCard label="Voucher uses" value={history.length} tone="gold" /><StatCard label="Card uses" value={giftHistory.length} tone="blue" /></div></div>{notice && <div className="notice">{notice}</div>}<div className="grid-two"><Section title="Available vouchers" eyebrow="DISCOUNTS"><div className="offer-grid">{vouchers.length ? vouchers.map((item) => <article className="offer" key={item.id}><span className="offer-code">{item.code}</span><strong>{item.discount}</strong><p>{item.description}</p><small>Expires {item.expiryDate} · {item.currentUsage}/{item.maxUsage} used</small><button className="button primary" onClick={() => redeemVoucher(item.code)}>Redeem voucher</button></article>) : <p className="empty">No active vouchers available.</p>}</div></Section><Section title="Available gift cards" eyebrow="STORED VALUE"><div className="offer-grid">{cards.length ? cards.map((item) => <article className="offer gold" key={item.id}><span className="offer-code">{item.code}</span><strong>{item.balance}</strong><p>Remaining balance</p><small>Expires {item.expiryDate}</small><button className="button primary" onClick={() => redeemCard(item)}>Redeem amount</button></article>) : <p className="empty">No active gift cards available.</p>}</div></Section></div><Section title="My Gift Card History" eyebrow="PERSONAL ACTIVITY"><DataTable columns={['Type', 'Code', 'Redeemed amount', 'Remaining balance', 'Redeemed at']} rows={[...history.map((x) => ['Voucher', x.voucherCode, x.discount, '-', x.redeemedAt]), ...giftHistory.map((x) => ['Gift card', x.giftCardCode, x.amount, x.remainingBalance, x.redeemedAt])]} /></Section></div>;
}
function DataTable({ columns, rows }) { return <div className="table-wrap"><table><thead><tr>{columns.map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length} className="empty">No redemptions yet.</td></tr>}</tbody></table></div>; }
